### ISSUE TITLE
Le README indique Flarum 0.1.0 Beta *15*

### ISSUE THREAD

**Issue by martignoni** [qiaeru/lang-french#23]
### Description

Le fichier README indique Flarum 0.1.0 Beta *15*, qui n'est pas encore sorti :-). Cela devrait être *14*, à mon humble avis

**Comment by qiaeru** [comment]
La version actuelle de la traduction sur GitHub est basée sur la future version de Flarum car elle représente une version en développement.

La dernière version stable de la traduction, disponible dans les "releases", est bien mis en beta 14.

Mais je mettrai effectivement bientôt un "-dev" à côté de la version, histoire que ce soit plus clair.

Merci de la remontée ! 😉

**Comment by martignoni** [comment]
Merci pour l’explication et pour la traduction surtout.

**Comment by qiaeru** [comment]
Fixed with https://github.com/qiaeru/lang-french/commit/fff243f4e0f0c9dfecb77a7f6be4305ea00ec085
