### ISSUE TITLE
Pas de prise en compte des traductions de la version 1.8.3

### ISSUE THREAD

**Issue by ouraios** [qiaeru/lang-french#25]
Version flarum 0.1.0-beta.14.1
La MAJ 1.8.3 de lang-french ne semble pas avoir était appliquée, pourtant j'ai bien vidé le cache navigateur et le cache côté serveur avec `php flarum cache:clear` rien n'y fait j'ai des traductions de date qui sont toujours en anglais : 

![image](https://user-images.githubusercontent.com/9526860/99921404-79c8a100-2d2a-11eb-827f-5126f645eaa5.png)
![image](https://user-images.githubusercontent.com/9526860/99921545-54886280-2d2b-11eb-9d12-23b0904b4717.png)

**Comment by qiaeru** [comment]
Merci bien ouraios. Décidément ,cette migration vers Day.js ne se fait pas sans douleur ! 😥

Au mois, ça reste utilisable. J'essaie de regarder ça vite !

**Comment by qiaeru** [comment]
Je viens de déployer la version 1.8.4 pour tenter de résoudre le problème.

Quand tu auras le temps, pourras-tu tester et me dire si ça fonctionne correctement s'il-te-plait ?
Pour le moment, je ne notifie pas la sortie de cette nouvelle version sur le forum car je ne peux actuellement pas tester.

**Comment by ouraios** [comment]
ça m'a tout pété :( 
![image](https://user-images.githubusercontent.com/9526860/100131466-5ca7e580-2e84-11eb-91a2-d58d8fd67db6.png)

**Comment by ouraios** [comment]
J'ai rollback sur la 1.8.3 qui fonctionne mieux en attendant ^^

**Comment by Magicalex** [comment]
Y a plus aucune traduction qui fonctionne maintenant

**Comment by Magicalex** [comment]
J'ai fix le bug, j'ai proposé une PR

**Comment by qiaeru** [comment]
Oui, je me doutais que ça allait mettre le bazar, c'est pour ça que j'ai évité de l'annoncer pour que ça impacte le moins de monde possible. Par contre, je ne sais pas si ça va régler le problème initial posé par ouraios ?...

En tout cas, merci beaucoup @Magicalex.

Si vous pouviez me faire un retour sur la prochaine version 1.8.5, que les dates et heures soient bien traduites, ce serait super ! 😉👍

**Comment by qiaeru** [comment]
Et voilà, la version 1.8.5 est publiée ! 😀

**Comment by Magicalex** [comment]
Pour moi c'est bon :)

**Comment by ouraios** [comment]
C'est tout bon pour moi aussi bravo à vous 2 les gars !!
