### ISSUE TITLE
Core version

### ISSUE THREAD

**Issue by zakariamehbi** [qiaeru/lang-french#29]
The core version in the requirement is not compatible.

`
$:~/www/flarum/html# composer require qiaeru/lang-french
Using version ^1.10 for qiaeru/lang-french
./composer.json has been updated
Running composer update qiaeru/lang-french
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires qiaeru/lang-french ^1.10 -> satisfiable by qiaeru/lang-french[v1.10.0].
    - qiaeru/lang-french v1.10.0 requires flarum/core ^0.1.0-beta.16 -> found flarum/core[v0.1.0-beta.16] but it does not match your minimum-stability.
`

**Comment by qiaeru** [comment]
A new version compatible with the 1.0.0 version of Flarum will be released very soon and should fix these issues. 😉
